---
- name: Setup AUR builder user
  ansible.builtin.include_tasks: aur_user.yml

- name: Install yay AUR helper
  ansible.builtin.include_tasks: aur_install_yay.yml

- name: Update pacman database
  become: true
  community.general.pacman:
    update_cache: true

- name: Upgrade all packages
  become: true
  community.general.pacman:
    upgrade: true

- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ packages }}"
    state: present

- name: Install AUR packages
  ansible.builtin.include_tasks: aur_packages.yml
