---
- name: Provision claude-home
  hosts: all

  vars_files:
    - ../vars/claude-home.yml

  roles:
    - role: network
      tags: [network]
    - role: packages
      tags: [packages]
    - role: claude
      tags: [claude]
